InvoicePlane/InvoicePlane

application/modules/mailer/controllers/mailer.php
Fixes issue #140 "Invoice is sent even if you cancel the email form". Now the button clicked in the email form is checked, and when if the cancel button was clicked the user is sent back to the list of invoices or quotes.
=> Do not send invoices/quotes when clicking the cancel button

application/modules/email_templates/views/form.php, application/modules/email_templates/views/index.php
Minor fix to display in the local language: the label "type" in the email templates form, and the type of email template (invoice or quote) in the list of templates.
=> Display type of email template in local language

application/modules/products/models/mdl_products.php, application/modules/products/views/modal_product_lookups.php
Fixed IP-175
- removed default_join for tax rates
- fixed new row id from products modal
Fix for IP-176:
- moved checkbox to a new column …
Fix for IP-177:
- added missing by_product() method in mdl_products
- product_description is no longer required
- purchase_price is no longer required
=> Added missing by_product() method

application/modules/import/models/mdl_import.php
Import now checks if needed headers exist - no matter in what order. Please check if this is ok, if yes, the same behaviour should be implemented for importing invoices and invoice items.
=> better check for headers on import

application/views/reports/sales_by_year.php
Not need to add € symbol when using format_currency function. 
Quarter could be written with space or slash (but no hyphen). See http://financial-dictionary.thefreedictionary.com/quarter. I prefer slash, because of it menas "of" (like 1st quarter of year...) more than space.
=> € symbol, quarter (small correction)

application/views/reports/payment_history.php
Adding a sum row to the payment history report. Currently looks like this:
Consider this a WIP, feedback welcome.
=> IP-232: Add sum to payment history

application/modules/dashboard/views/index.php
The link was broken if IP was run from a subdirectory of the domain (e.g. http://example.com/ip/).
Now it uses the `anchor` function that properly appends the url prefix to the link.
I hope this is the right branch since I couldn't find a `hotfix` branch for patch releases.
=> Fixes relative link of the 'overdue invoices' dashboard panel.

application/helpers/country-list/en/country.php, application/helpers/country-list/id/country.php
The official country name of "The Netherlands" includes "The".
=> Fixed country name of "The Netherlands" in the country lists

application/modules/products/models/mdl_products.php, application/modules/products/views/form.php
Also optimized the tax rate displaying.
=> IP-287 - “Create product” without a valid “Family” throws SQL/PHP error

assets/default/sass/_upload.scss
No matter how the proportions of the logo were, it was always displayed as fixed 80x80px - this looked distorted if the logo is e.g. 200x40px.
=> fix logo upload image width/height proportions

.htaccess
It's much more convenient if you just need to remove some comment hashs.
=> Add (disabled) option to force HTTPS access

application/errors/error_404.php
An updated 404 error page. Cleaner, simpler with no container.
- Now responsive + viewport set.
- Removed ‘404’ from the page title. No need for this, users just need
to know that the page was not found. The number is a side note.
- Added ‘InvoicePlane’ to the title, so that the user knows its apart
of the InvoicePlane environment.
- Updated the ‘code’ element styling to be a bit simpler. I wasn’t sure
if this was actually needed, as I only see ‘p’ tags coming through.
=> Updated 404 Page

application/modules/settings/views/partial_settings_email.php
Moved email pdf attachment setting (HTML) out of SMTP tab/section and made it a global email setting. The setting already applies to all email methods (in the backend), its just that it was tucked away in the SMTP tab on the frontend.
I've tested this and the setting applies to phpmail, sendmail, and smtp.
=> Fix: Email PDF attachement now global

application/modules/invoices/models/mdl_invoice_amounts.php, application/modules/invoices/models/mdl_item_amounts.php, application/modules/quotes/models/mdl_quote_amounts.php, application/modules/quotes/models/mdl_quote_item_amounts.php
Some calculation have been modified. Instead of using normal math operations, _bcmath_ functions are used if the module is available. When _bcmath_ is not available, normal calculation is performed.
=> Added some optional support for bcmath

application/modules/clients/views/form.php
If you're using switches with colons, you're not allowed to keep a space between the switch and the case.
This will cause syntax errors, like these:
PHP Parse error: syntax error, unexpected '', expecting endswitch (T_ENDSWITCH) or case (T_CASE) or default (T_DEFAULT) in form.php on line 200
See http://php.net/manual/en/control-structures.alternative-syntax.php
=> Fixed syntax error in clients form

composer.json
Removed PayPal and Stripe from composer.json as they are already included in omnipay/omnipay
=> IP-317 - Removed PayPal and Stripe from composer.json

application/helpers/mpdf_helper.php, application/helpers/pdf_helper.php, application/language/english/ip_lang.php, application/modules/settings/controllers/settings.php, application/modules/settings/views/partial_settings_invoices.php
When is was designing the invoice PDF template I wanted to use my company's corporate identity to style the invoice. Redesigning this in HTML is a real pain in the ass, while a simple PDF file could fix the problem. This pull request implements the [mPDF template feature](http://mpdf1.com/manual/index.php?tid=349) (not to be confused with the InvoicePlane templating system). To use it, save a template PDF file to `uploads/pdf_base.pdf`. Make sure the body background-color is set to `none`. Normalize.css defaults to white, which while overlay the template.
=> IP-360 - Implemented mPDF template file

application/modules/invoices/models/mdl_invoices.php, application/modules/quotes/models/mdl_quotes.php
When a invoice or quote is duplicated, from now on the custom fields will be copied along with it. The `copy_invoice()` method is also used for the recurring invoice cron, therefore recurring invoices also get the custom fields of their parent.
=> IP-104 - Custom fields are not copied when Invoice is duplicated

application/helpers/pdf_helper.php, application/modules/invoice_groups/controllers/invoice_groups.php, application/modules/invoice_groups/models/mdl_invoice_groups.php, application/modules/invoice_groups/views/form.php, application/modules/setup/sql/017_1.4.4-nextRelease.sql
This commit adds a extra select in invoice groups for choosing a custom default template. In case there is no template selected everything works as before.
This allows us having different templates for different kinds of documents (proforma/delivery note/...)
There is a small change in database (see application/modules/setup/sql/017_1.4.4-nextRelease.sql). I didn't know where to put this change so rename this file as you like.
PD: This is a reborn of pull request #333
=> IP-109: Added suport for having a custom template for each invoice group

application/modules/import/models/mdl_import.php, application/modules/invoices/models/mdl_invoices.php, application/modules/invoices/models/mdl_items.php, application/modules/quotes/controllers/ajax.php, application/modules/quotes/models/mdl_quote_items.php, application/modules/quotes/models/mdl_quotes.php
I think the commit https://github.com/InvoicePlane/InvoicePlane/commit/de08ee0b4bd00e21a5a32e74b14fd1a1213967e0 broke both invoice copying and recurring invoices: When copying invoices in v1.4.5, the items don't get copied and recurring invoices are also missing the items.
This PR removes the first arguments of all calls to `mdl_items->save`, `mdl_invoice_tax_rates->save`, `mdl_quote_items->save` and `mdl_quote_tax_rates->save`.
It also removes the wrong object access to `invoice_id` and `quote_id` in `mdl_items.php` and `mdl_quote_items.php`.
=> Fix invoice copy (and recurring)

application/helpers/mpdf_helper.php
IP-400 fix null password PDF protection.
Avoid setting any protection when $password is null/"empty"
=>  IP-400 fix null password PDF protection

application/helpers/mpdf/includes/functions.php, application/helpers/mpdf/mpdf.php, application/helpers/mpdf_helper.php, application/helpers/pdf_helper.php, application/helpers/zugferd_helper.php, application/language/english/ip_lang.php, application/libraries/ZugferdXml.php, application/modules/invoices/controllers/invoices.php, application/modules/invoices/models/mdl_items.php, application/modules/settings/views/partial_settings_general.php
This PR enables creation of ZUGFeRD Invoices in InvoicePlane. A good technical description of the format is available on http://www.pdflib.com/knowledge-base/pdfa/zugferd-invoices.
Two routes are concerned in IP:
- GET XML standalone via ```invoices/generate_zugferd_xml/{invoice_id}```
- GET XML embedded in the PDF via ```invoices/generate_pdf/{invoice_id}?include_zugferd_xml=true```
Note: 
- ZUGFeRD requires an ISO currency code: I've added it in the system settings, like the actual "currency symbol" https://github.com/InvoicePlane/InvoicePlane/commit/50c8ddbe4e84eb25c2b83ce278e902a67eac45c7
- ZUGFeRD requires PDF/A-3: I've adapted mPDF library here, but the same code is in a PR on mPDF: https://github.com/mpdf/mpdf/pull/130
Don't hesitate to ask for modifications, i'll be glad to help!
=> IP-412 - ZUGFeRD PDF invoices

application/modules/invoices/controllers/ajax.php, application/modules/invoices/views/modal_add_invoice_tax.php, application/modules/invoices/views/partial_item_table.php, application/modules/quotes/controllers/ajax.php, application/modules/quotes/views/modal_add_quote_tax.php, application/modules/quotes/views/partial_item_table.php, application/modules/tax_rates/views/form.php, application/views/invoice_templates/pdf/InvoicePlane - overdue.php, application/views/invoice_templates/pdf/InvoicePlane - paid.php, application/views/invoice_templates/pdf/InvoicePlane.php, application/views/invoice_templates/public/InvoicePlane_Web.php, application/views/quote_templates/pdf/InvoicePlane.php, application/views/quote_templates/public/InvoicePlane_Web.php
[IP-435] format_amount() and standardize_amount() wasn't used for taxes, now they
are so taxes get localized too and are able to be saved
=> [IP-435] Fixed localization problems for taxes

application/modules/invoices/views/modal_create_invoice.php, application/modules/quotes/views/modal_create_quote.php
When creating a quote or invoice for a client who has an apostrophe in
their name, it created malformed HTML for the client select list because
it used single quotes in the option value attribute. This commit changes
it to use double quotes.
=> Fix invoice creation for clients who have apostrophes in their names.

.dockerignore, Dockerfile
I have spent days now struggling with existing Docker images. Searching for InvoicePlane errors like "white screen after database connection" has been very unhelpful. Please merge this to help any poor souls like me in the future.
We should also get an official InvoicePlane image up on Docker Hub. I can help with that if you'd like.
This has a few advantages this has over [the existing images](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=InvoicePlane&starCount=0).
* **It's simple.** There is nothing complex about this image. It exposes port 80 by default, runs Apache in the foreground automatically, and makes no assumptions about what directories you want to mount.
* **It's based on the official PHP base image.** Other existing images use custom base …
=> IP-447 - Added Dockerfile

application/modules/invoices/models/mdl_invoices.php, application/views/invoice_templates/pdf/InvoicePlane.php
The invoice templates can now use the information from quotes and custom quotes.
E.g. I am adding the contact person or the person who requested the quote.
Thus I can add the 
* quote_number,
* the requester and
* the contact person 
in the invoice template.
See https://community.invoiceplane.com/t/topic/3860/8
Please squash the PR.
=> Add quote information to invoices - IP-476

application/views/invoice_templates/pdf/InvoicePlane - overdue.php, application/views/invoice_templates/pdf/InvoicePlane - paid.php, application/views/invoice_templates/pdf/InvoicePlane.php, application/views/quote_templates/pdf/InvoicePlane.php
This PR changes the format of the client postal address in PDF templates.
Issue: [[IP-477] Nonstandard address format in templates](https://development.invoiceplane.com/browse/IP-477)
```
{{ Address 1 }}
{{ Address 2 }}
{{ City and/or ZIP Code }}
{{ State }}
```
```
{{ Address 1 }}
{{ Address 2 }}
{{ City }} {{ State }} {{ ZIP Code }}
```
=> Fix address formatting in PDF templates - IP-477

application/modules/layout/views/layout.php
Benefits:
- More consistent design.
- Less ’noise’.
- If user and company name is long, it breaks onto a new line at
certain screen sizes, this should be more compact and stop that in most
cases.
[Original Header](http://pasteboard.co/xk6c2Nvig.png)
[New Header](http://pasteboard.co/xk6UGa9to.png)
[New Header Mobile](http://pasteboard.co/xk7pYIeWZ.png)
=> Suggestion: replaced header menu bar username / company text with icon

application/modules/layout/views/layout.php, application/modules/layout/views/layout_guest.php
The script itself moves the `title` to `data-original-title`. That way
the `title` attribute can be a fallback when JS is not enabled. I
believe this is the "correct" way to use this plugin.
Not a biggie, just a suggestion.
=> Suggestion: "data-original-title" to "title" attribute

application/language/english/ip_lang.php, application/modules/invoice_groups/models/Mdl_invoice_groups.php, application/modules/invoice_groups/views/form.php
This allows invoice groups to use a two digit year format
like {{{yy}}}} in the invoice numbers.
This way in 2017 an invoice number may contain >>17<<.
Closes IP-488
=> 2-digit year format for invoice and quote numbers

assets/default/sass/style.scss
Moved the css to a wider media query so they are on the same line the whole time the mobile menu is active, previously it only occurred at the smaller size.
[Tablet menu without fix](http://pasteboard.co/y7VURAlU5.png)
[Tablet menu with fix](http://pasteboard.co/y7WGmReS4.png)
=> CSS improvement: icons on same line as text in rest. menu

application/helpers/pdf_helper.php, application/modules/invoices/views/partial_item_table.php
- Switch to trans() in partial_item_table: This way if the text isn't translated in another language it still appears in English
- Set a more descriptive filename: Sumex Invoices now when generated have a more descriptive name like `Invoice_INV-20170218_196bb16d.pdf` (instead of `doc.pdf`)
=> Switch to trans() in partial_item_table

application/modules/clients/controllers/Ajax.php
Ajax type-ahead for client names would'nt return results if you started typing "ohn" or "hn" while searching for a client named "John Doe" for example.
It now does.
https://community.invoiceplane.com/t/topic/4471/3
=> Added more effective search results on client names - IP-544

application/modules/tasks/models/Mdl_tasks.php
Due to a wrong database column it was not possible to delete projects.
This is now fixed.
=> Make it possible to delete projects

application/modules/guest/views/payment_information.php
The download link can be found at url `/guest/payment_information/form/ULm****VxoWR60q` where `ULm****VxoWR60q` is your invoice url key.
On a side note: it seems like such links can be forged/reached by the guest even if you set "online payments" to "disabled".
=> fixed broken download url

application/modules/dashboard/views/index.php, application/modules/upload/views/dropzone-quote-scripts.php
- Fixed a bug where attached image files would point to a broken url and would not render (missing trailing slash).
- Changed `window.open` to `location.href` due to UX concerns.
On a side note: `$config['csrf_regenerate']` should be set to `false` within `/application/config/config.php` for the upload form to work properly. Otherwise you will not be able to upload consecutive files (csrf token 403 error).
=> download link bug fix

application/modules/invoices/controllers/Ajax.php, application/modules/settings/views/partial_settings_general.php
Fixed a scenario where a user would inadvertently add a new line for a new item and could not save the invoice or could not delete the empty item: "The Article field is required."
=> Fixed fully empty item throwing an error

application/modules/users/models/Mdl_users.php
https://development.invoiceplane.com/browse/IP-624
It was using a custom function which had the same check than CI's default one without any error message which produces an error (https://gyazo.com/dcc16f474a781db09141eba1a301f538) 
I've tested with 
> mark@github.design
And it works perfectly, it was accepted (as it seems the old function of CI2 didn't accept new TLD's)
=> [IP-624] - Use default function valid_email() of CI

application/modules/invoices/controllers/Invoices.php
https://development.invoiceplane.com/browse/IP-620
If you want to download archives with space inside the name, it result in a corrupted file as it transforms space with `%20`.
It needs to have urldecode inside the `header` and `read_file` function to work properly and download without being corrupted.
=> [IP-620] - Invoice name with space results in corrupted in archive page

application/views/invoice_templates/public/InvoicePlane_Web.php, application/views/quote_templates/public/InvoicePlane_Web.php
I don't know why it was setup like that as it attends to go in a controller to generate the file and not download with a direct link.
So I've changed it to site_url() to also get index.php if not removed (otherwise it produces a 404 not found)
(Follow this topic : https://community.invoiceplane.com/t/topic/5194/5 it can have a link)
=> fix download link

application/modules/invoices/models/Mdl_invoices.php, application/modules/mailer/controllers/Mailer.php, application/modules/quotes/models/Mdl_quotes.php
https://development.invoiceplane.com/browse/IP-602
The function to generate invoice number was done after the mail is sent that's why the invoice number didn't exist in the mail.
=> [IP-602] & [IP-603] - Invoice/Quote number generated after sent

assets/core/js/scripts.js
> jQuery.html() treats the string as HTML, jQuery.text() treats the content as text.
That's why the template was not displayed but interpreted.
=> [IP-543] - HTML mail templates not working

application/modules/guest/controllers/Payment_handler.php
Change the verification from "on" to "1" as it's saved with 0/1 in DB. So it needs to fit the actual settings to enter in the condition and use correctly the test mode.
https://development.invoiceplane.com/browse/IP-652
The fix has been tested (cf community post)
=> [IP-652] - Paypal sandbox not working

application/modules/clients/views/form.php, application/modules/invoices/views/modal_create_invoice.php, application/modules/invoices/views/view.php, application/modules/payments/views/form.php, application/modules/quotes/views/modal_create_quote.php, application/modules/quotes/views/view.php, application/modules/settings/views/partial_settings_email.php, application/modules/settings/views/partial_settings_general.php, application/modules/settings/views/partial_settings_invoices.php, application/modules/settings/views/partial_settings_projects_tasks.php, application/modules/settings/views/partial_settings_quotes.php, application/modules/settings/views/partial_settings_taxes.php, application/modules/tasks/views/form.php
Remove the search box from the Select2 dropdown lists when not needed. For instance, when there is a short number of options or options are hard coded (e.g. yes/no questions). Fixed by adding 'data-minimum-results-for-search="Infinity"' to the select tag as suggested in:
- https://stackoverflow.com/questions/17480040/select2-hiding-the-search-box (in particular, Aaron Hudon's answer)
- https://github.com/select2/select2/issues/3199
- https://github.com/select2/select2/issues/3189
=> [IP719]  Remove search box from Select2 dropdown lists when not needed

application/modules/invoices/views/partial_item_table.php, application/modules/quotes/views/partial_item_table.php
Reorder the elements in the tax line in invoice & quote views to display the amount at the right end of the line as in:  [trash-icon] US Std 7,00% 28,00€
=> [IP-745] Reorder tax line in invoice & quote views

application/modules/invoices/controllers/Ajax.php, application/modules/invoices/controllers/Invoices.php, application/modules/invoices/views/view.php, application/modules/layout/views/includes/head.php, application/modules/payments/controllers/Ajax.php, application/modules/payments/views/modal_add_payment.php
When creating an invoice payment through the modal window "Enter Payment" and clicking the [save] button, if there are payment custom fields take the user to the payment form so that (s)he can fill them before saving the payment, Otherwise, return to the invoice form.
=> [IP-728] Display payment form if there are custom fields

assets/core/js/scripts.js, package.json
In order to fix some clipboard issues we needed to include clipboardjs.
Then i made sure it was included in the package.json
And in the Gruntfile.js it needs to be compiled to dependencies.js
Finally in /assets/core/js/scripts.js we need to call ClipboardJS instead of Clipboard (current)
=> Fixing clipboard issues

application/modules/quotes/models/Mdl_quote_items.php
Make $item->product values available in quotes (just as they are in invoices) as announced in the forum https://community.invoiceplane.com/t/topic/9188
=> Make product.* available in quotes

.gitignore, application/modules/payments/views/form.php
When a payment method exists on the invoice, the select is disabled with the wrong option selected.  Set the select value and trigger a change so that select2 re-renders the selected value.
* [X ] My code follows the code formatting guidelines.
* [x ] Bugfix
=> Fix Payment Method Select

application/libraries/ZugferdXml.php
This PR fixes the issue #809. If the client name has an & in their name, it would break PDF generation otherwise.
=> Escape client name for PDF generation (Only in Zugferd invoices)

application/config/payment_gateways.php, application/modules/guest/controllers/Payment_handler.php, application/modules/guest/controllers/Payment_information.php, application/modules/guest/views/gateway/stripe.js, application/modules/guest/views/gateway/stripe.php, application/modules/guest/views/payment_information.php
=> Fix for outdated card data handling #814

application/config/database.php, application/helpers/date_helper.php, application/helpers/echo_helper.php, application/modules/clients/views/form.php, application/modules/dashboard/views/index.php, application/modules/guest/views/gateway/stripe.php, application/modules/import/models/Mdl_import.php, application/modules/invoices/controllers/Cron.php, application/modules/invoices/models/Mdl_invoice_amounts.php, application/modules/invoices/views/view_sumex.php, application/modules/mailer/controllers/Mailer.php, application/modules/quotes/models/Mdl_quote_amounts.php, application/modules/settings/controllers/Settings.php, application/modules/settings/models/Mdl_settings.php, application/modules/settings/views/partial_settings_general.php, application/modules/settings/views/partial_settings_online_payment.php, application/modules/tasks/views/form.php, application/modules/tasks/views/index.php, application/third_party/MX/Controller.php, application/third_party/MX/Loader.php, application/third_party/MX/Modules.php, composer.json, composer.lock, index.php, ipconfig.php.example
PHP8.1 compatibility changes - see #798 
https://php.watch/versions/8.1
Testing progress against PHP8.1
=> PHP8.1 compatibility

application/core/Base_Controller.php, application/modules/settings/models/Mdl_settings.php, application/modules/setup/controllers/Setup.php, application/third_party/MX/Controller.php, application/third_party/MX/Loader.php, application/third_party/MX/Modules.php
=> Fix the php8.1 migration

application/modules/setup/sql/035_1.5.12.sql
the length of the field by varchar(100) is enough (since login table uses the same length) and provides additional security. Closes #886 
=> [IP-886]: login_log fields length correction

application/modules/guest/views/payment_information.php
known issue was not completely solved in beta version. Stripe library is now loaded by passing a php script instead of injecting js directly. IP must therefore use site_url variable instead of base_url.
#883
=> fix loading stripe for websites not using clean urls (#883)

assets/core/js/scripts.js
When selecting an email template on the 'send invoice' page, it won't get inserted into the textarea. val() instead of html() has to be used here.
Fixes the above mentioned issue.
=> Fix: Inserting email template

.gitignore, application/language/english/ip_lang.php, application/modules/invoices/models/Mdl_invoices.php, application/modules/mailer/controllers/Mailer.php, application/modules/settings/views/partial_settings_invoices.php
As indicated in the problem (#895), when sending the invoice, the invoice date and due date are not changed. 
Those details are retained as set when the invoice is created, even if changes are made in the period (days, weeks) thereafter. 
My solution will always "by default" change the invoice date to the current date and also recalculate the due date, **IF the setting** _**[Disable the change of invoice date and due date before emailing]**_ **is NOT activated BEFORE SENDING THE EMAIL!** 
So if the setting is **active** then the invoice date and due date are NOT changed.
#895 
For me, this is a problem/rectification that needs to be resolved
https://github.com/InvoicePlane/InvoicePlane/issues/895
=> IP-895: Option to Initiate Terms When Sending Invoice (WIP)

.gitignore, application/language/english/ip_lang.php, application/modules/invoices/models/Mdl_invoices.php, application/modules/mailer/controllers/Mailer.php, application/modules/settings/views/partial_settings_invoices.php
See #924 --> must reopen it to re-revert
As indicated in the problem (#895), when sending the invoice, the invoice date and due date are not changed. 
Those details are retained as set when the invoice is created, even if changes are made in the period (days, weeks) thereafter. 
My solution will always "by default" change the invoice date to the current date and also recalculate the due date, **IF the setting** _**[Disable the change of invoice date and due date before emailing]**_ **is NOT activated BEFORE SENDING THE EMAIL!** 
So if the setting is **active** then the invoice date and due date are NOT changed.
#895 
For me, this is a problem/rectification that needs to be resolved
https://github.com/InvoicePlane/InvoicePlane/issues/895
=> IP-895: Option to Initiate Terms When Sending Invoice

application/views/quote_templates/pdf/InvoicePlane.php
It seems that the default pdf quote template contains an error.
If you use the "state field" then it will be shown twice in the quote pdf.
closes issue #840 
#840 I deleted the redundant field "State" in the default IP Quote pdf template file.
=> Fix bug #840 Deleted the extra "state" field

application/modules/setup/controllers/Setup.php
After installing InvoicePlane, the ENCRYPTION_KEY should be set
#959 
1. Clean install of InvoicePlane
2. Before installing, check the ipconfig.php file
3. Value of Encryption Key is: `ENCRYPTION_KEY=`
4. After installing, Value of Encryption Key is: `ENCRYPTION_KEY=`
=> [IP-959]: set encryption key after installing

application/helpers/invoice_helper.php
Fix bug where logo wasn't found while creating PDF invoice
When you create PDF invoice, the logo is fetched, but somehow the appropriate path isn't generated properly.
This PR fixes that bug
=> 898: Fix bug where logo wasn't found while creating PDF invoice

application/modules/clients/models/Mdl_clients.php, application/modules/custom_fields/models/Mdl_custom_fields.php, application/modules/email_templates/models/Mdl_email_templates.php, application/modules/mailer/controllers/Mailer.php, application/modules/quotes/controllers/Ajax.php, application/modules/sessions/controllers/Sessions.php
Fix some security vulnerabilities
Fixed a number of security vulnerabilities:
|           |   FileName     | FieldName | Fix type  |
|-	        |-	    |-            |-	            |
|  X   |`Mdl_email_templates.php`| `from_name`  | trim/xss_clean |
|  X   |`Mdl_clients.php`| `client_language` | trim/xss_clean |
|  X   |`Mdl_clients.php`| `client_country`  | trim/xss_clean |
|  X   |`Mdl_custom_fields.php`| `is_natural`  | xss_clean |
|  X   |`Mailer/Controllers/Mailer.php`| `to_email` | **default** xss_clean |
|  X   |`Quotes/Controllers/Ajax.php`| `quote_id` | **default** xss_clean |
|  X   |`Sessions/Controllers/Sessions.php`| `token` | check for alpha numeric characters |
|  X   |`Sessions/Controllers/Sessions.php`| `email` | check for proper email address |
=> security fixes

application/modules/setup/controllers/Setup.php
Sometimes a user isn't created during installation process. At this time all we can do is add logging.
I've also added a check whether there are 0 users in the database after the 'create_user' step.
If 0 users, redirect to 'create_user step'
addresses #968 
It's a pain to add user manually after setup is complete:
1. Open ip_users table
2. Add user manually plus set password in a certain way.
3. These steps were discussed on the forums: https://community.invoiceplane.com
=> [IP-968] Sometimes a user isn't created, add more logging to see what's going on

application/modules/settings/models/Mdl_settings.php
Since Windows uses `\` as a folder separator, this causes the problem that the list of themes in the settings is empty.
=> Show list of themes on Windows

application/modules/setup/controllers/Setup.php
=> Fix for issue 1038: Wrong translation string in setup

application/libraries/ZugferdXml.php
Add the ability in `xmlSellerTradeParty` to switch between company and person billing by adding company name in customer company field
Fixes #1078
=> [IP-1078]: ZUGFeRD Name should not be user name

application/modules/invoices/views/modal_copy_invoice.php, application/modules/quotes/models/Mdl_quotes.php, application/modules/quotes/views/modal_copy_quote.php
The ajax form doesn't post because there is **no response** from the backend.
The problem comes when fetching the 'custom_fields' data.
As far as I understand it, the ( existing?) data is retrieved from the custom_fields db and put into an array.
If there is no data in the db the array cannot be populated and as a result of this there is no "response".
Therefore, in modal_copy_quote, the code
```
if (response.success === 1) {
window.location = "<?php echo site_url('invoices/view'); ?>/" + response.invoice_id;
}
```
is not executed in order to close the modal window and to display the copied quote view page.
To solve the problem I extracted the snippet (copied the custom_fields code) from mdl_invoice.php and modified it in mdl_quotes.php.
#841 Copy quote (modal) UI feedback
#841 See …
=> [IP-841]: Copy Quote UI feedback

application/views/invoice_templates/pdf/InvoicePlane - overdue.php, application/views/invoice_templates/pdf/InvoicePlane - paid.php, application/views/invoice_templates/pdf/InvoicePlane.php, application/views/quote_templates/pdf/InvoicePlane.php
Making sure all the fields in the templates are escaped by htmlspecialchars
To make sure we don't get unintended output in our PDF files, we're surrounding every output by the `_htmlsc()` function, which is basically htmlspecialchars
To be determined
Just something that needed to be done
=> Make sure we don't get unintended output in our PDF files

application/libraries/QrCode.php
When an invoice is paid in part. The QR code always displays the total paid, not what remains to be paid.
#1128
Avoid paying my customer twice for an amount that is already half paid.
As for the branch. I'm having a bit of trouble understanding the variety of branches that InvoicePlane currently has. I didn't check the last two checklists because of this.
=> Update QrCode.php wrong variable

application/modules/clients/controllers/Ajax.php, application/modules/clients/models/Mdl_client_notes.php, application/modules/clients/views/partial_notes.php, application/modules/clients/views/view.php
Fix Impossible to delete client notes (Only option it's del client...)
Now, all notes have **delete button** by Ajax (see below)
Fix if .has-error never dropped.
=> Add buttons on client view to delete note (Ajax)

application/modules/setup/models/Mdl_setup.php, application/modules/setup/sql/037_1.6.1.sql, application/modules/setup/sql/038_1.6.2.sql, application/modules/setup/sql/039_1.6.2.sql
See : [IP-1003: Add extra field title (#1101)](https://github.com/InvoicePlane/InvoicePlane/commit/c64b5df878aeb351e312a75c9cc60de33b91c810#diff-f97132f81d846a5d14eb35d66fe77c943572d8db71735702e6f018f65671058c)
Devs, After need update DB Like this:
```sql
UPDATE `ip_versions` SET
`version_id` = '38',
`version_date_applied` = '1734693462',
`version_file` = '037_1.6.1.sql',
`version_sql_errors` = '0'
WHERE `version_id` = '38';
UPDATE `ip_versions` SET
`version_id` = '39',
`version_date_applied` = '1734693462',
`version_file` = '038_1.6.2.sql',
`version_sql_errors` = '0'
WHERE `version_id` = '39';
```
Maybe  #1147 
No Problem when upgrade from 1.5.11,
Fix file in db ip_version table (missing 1.6.1.sql & twice 1.6.2.sql)
=> Fix setup sql filenames

application/views/invoice_templates/public/InvoicePlane_Web.php
In the default invoice web template, if the invoice is paid, a PHP error is rendered in place of the QR code.
This happens because the invoice_qrcode() function expects a balance greater than or equal to 0.01, to use as the transaction amount in the QR data.
This PR solves this issue by checking that the invoice balance is > 0 before rendering the QR code element
(similar to the default invoice PDF templates, where in the default paid template, there is no QR section).
=> Check invoice balance before rendering QR code in web view

application/modules/email_templates/views/template-tags-invoices.php, application/modules/settings/controllers/Settings.php, application/modules/settings/views/partial_settings_general.php
Now Custom Fields ip_invoice_custom is present in settings page
------------------
+ Remove hard fix in view template-tags-invoices
+ Indents of settings view partial_settings general
=> Fix #1169 : Add custom_fields in controllers/Settings

application/modules/clients/views/partial_client_table.php, application/modules/dashboard/views/index.php, application/modules/invoices/views/partial_invoice_table.php, application/modules/payments/views/partial_payment_table.php, application/modules/products/views/index.php, application/modules/products/views/partial_product_table_modal.php, application/modules/quotes/views/partial_quote_table.php, application/modules/tasks/views/index.php, application/modules/tasks/views/partial_task_table_modal.php, assets/core/scss/_core.scss
Improve #1185
Scope:
+ Clients
+ DashBoard
+ Invoices
+ Quotes
+ Payments
+ Products
+ Tasks
Note: .amount.last apply padding in last element like Quotes list
No
Good alignment for All table with amounts (th and tr)
=> Style2class for amounts & balances (th & tr)

application/helpers/template_helper.php
First solution of #1198 implemented
#1198
Solve a problem with `{{{invoice_status}}}` tag in remittance qr code text.
Edit: And in email body [see this comment](https://github.com/InvoicePlane/InvoicePlane/issues/1198#issuecomment-2594076307) (and maybe other).
Sent
Draft
=> Add invoice_status case in template_helper (Fix #1198)

application/helpers/template_helper.php
This update will use written label instead of option number in email template, if the filed is an custom field with single choice
solves https://community.invoiceplane.com/t/topic/10911
Using a custom field which is single choice in email templates is returned as number (of selected option) instead of text. This fix will return the chosen text.
=> Update template_helper.php to fix email template with custom single choice field

application/helpers/XMLconfigs/Facturxv10.php, application/helpers/XMLconfigs/Ublexamv20.php, application/helpers/XMLconfigs/Zugferdv10.php, application/helpers/mpdf_helper.php, application/helpers/pdf_helper.php, application/libraries/XMLtemplates/Facturxv10Xml.php
Add valid xml template for Factur-X
Inspired by template zugferd 1 of @Verony-makesIT 
- For user without VAT
- - <del>Complete IP VAT-ID field (With like 'FR') for clients & users to activate</del> (from old verony branch)
- - - To be validated, No VAT-ID in xml
- - and never set product tax (if `tax == 0` go to "Not subject to VAT" mode)
=> Add to Feature/939 : facturx10 (zugferd23 compat) e invoicing xml template

application/modules/invoices/models/Mdl_invoices.php
fixes #1218 
The invoices are sorted by ascending `invoice_id`. If you work a lot with drafts that are open for a few days before they are assigned the correct date and an invoice number, the list gets very mixed up. The list should be sorted by date (or alternatively by assigned number).
=> sort invoices by date instead of id

application/modules/quotes/models/Mdl_quotes.php
see #1218 to apply same thing of #1219 for quotes
Before
After
#1218
=> sort quotes by date instead of id

application/config/config.php, application/helpers/pdf_helper.php, application/libraries/XMLtemplates/Facturxv10Xml.php, application/modules/guest/controllers/View.php, application/modules/invoices/controllers/Ajax.php, application/modules/invoices/controllers/Invoices.php, application/modules/invoices/models/Mdl_invoice_amounts.php, application/modules/invoices/models/Mdl_invoice_tax_rates.php, application/modules/invoices/models/Mdl_item_amounts.php, application/modules/invoices/models/Mdl_items.php, application/modules/invoices/views/partial_itemlist_responsive.php, application/modules/invoices/views/partial_itemlist_table.php, application/modules/quotes/controllers/Ajax.php, application/modules/quotes/controllers/Quotes.php, application/modules/quotes/models/Mdl_quote_amounts.php, application/modules/quotes/models/Mdl_quote_item_amounts.php, application/modules/quotes/models/Mdl_quote_items.php, application/modules/quotes/models/Mdl_quote_tax_rates.php, application/modules/quotes/models/Mdl_quotes.php, application/modules/quotes/views/partial_itemlist_responsive.php, application/modules/quotes/views/partial_itemlist_table.php, application/views/invoice_templates/pdf/InvoicePlane.php, application/views/invoice_templates/public/InvoicePlane_Web.php, application/views/quote_templates/pdf/InvoicePlane.php, application/views/quote_templates/public/InvoicePlane_Web.php, ipconfig.php.example
+ Return to item subtotal = quantity * price
+ Calculate item discount on item subtotal
+ Calculate global (Q&I) discount on item subtotal
+ All taxes calculation with item subtotal discounted (wip)
---
global (Q&I) discount dispatched Proportionally by item
And not apply in Mdl_invoice_amount->calculate_discount()
---
In mdl tax rate (invoice) removed:
$this->mdl_invoice_amounts->calculate_invoice_taxes($invoice_id);
It Called in calculate (in test, same as quote. Maybe old)
Fix missing currency_symbol on price (Add new item)
In partial_itemlist_table (quote & invoice)
=> Amounts calculation: Legacy or not

application/helpers/number_helper.php
Solve a problem of open issue #1227
To Fix European number format change amount on save when use dot as comma
See **expected** image on #1227
=> Improve number_helper & standardize_amount (fix european format)

application/views/invoice_templates/pdf/InvoicePlane - overdue.php, application/views/invoice_templates/pdf/InvoicePlane - paid.php, application/views/invoice_templates/pdf/InvoicePlane.php, application/views/quote_templates/pdf/InvoicePlane.php, assets/invoiceplane/sass/templates.scss
This will add pagination to the default invoice and quote pdf templates
By doing it this way, one could still modify the template to remove pagination or move it to a different place inside the document.
Fixes https://github.com/InvoicePlane/InvoicePlane/issues/1234
=> Add pagination to invoice and quote templates

composer.json, composer.lock
Removing version string from `composer.json` file which resulted in validation errors.
Before changes:
```
$ composer validate --strict --no-interaction --no-check-all --no-check-lock
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
- The version field is present, it is recommended to leave it out if the package is published on Packagist.
```
after changes
```
$ composer validate --strict --no-interaction --no-check-all --no-check-lock
./composer.json is valid
```
This fixes building InvoicePlane on NixOS
Please check the following steps before submitting your PR. If any items are incomplete, consider marking it as `[WIP]` (Work in Progress).
---
Provide a brief description of the changes made in this pull request. …
=> composer.json omit version string
