InvoicePlane/InvoicePlane

- application/modules/users/models/mdl_users.php
- application/modules/users/views/form.php
Display company field in the user account screen so that it can be defined and used in the email templates.
> Display company field in user account screen

- application/config/config.php
- application/config/hooks.php
- application/hooks/SetTimezoneClass.php
- application/language/english/ip_lang.php
- application/modules/setup/controllers/setup.php
- application/modules/setup/views/prerequisites.php
Same as #155 but for hotfix-1.1.2.
> 1.1.2 Fix issues with missing timezone

- application/language/english/ip_lang.php
- application/modules/layout/views/layout.php
Use lang specific datepicker labels and day order. Needs to update language file, to config first day of week.
> Datepicker - lang specific

- README.md
- application/language/english/ip_lang.php
- application/modules/families/controllers/families.php
- application/modules/families/models/mdl_families.php
- application/modules/families/views/form.php
- application/modules/families/views/index.php
- application/modules/layout/views/layout.php
- application/modules/products/controllers/products.php
- application/modules/products/models/mdl_products.php
- application/modules/products/views/form.php
- application/modules/products/views/index.php
- application/modules/setup/sql/005_1.1.2.sql
- application/modules/setup/sql/006_1.1.2.sql
Added two modules for products and families management
> Products and products families

- application/helpers/date_helper.php
> Another date format

- application/modules/products/controllers/ajax.php
- application/modules/products/models/mdl_products.php
- application/modules/products/views/form.php
- application/modules/products/views/index.php
- application/modules/products/views/modal_product_lookups.php
Avoid using non-defined variable when joining an empty taxes table
Better handling of join problems using default values
> IP-179 fix

- application/modules/invoices/controllers/ajax.php
- application/modules/invoices/views/view.php
- application/modules/setup/sql/007_1.2.1.sql
IP-196 it's done. Now, you can select in a combobox the payment method of the invoice.
> IP-196 done

- application/modules/invoices/models/mdl_invoices.php
- application/modules/invoices/views/modal_create_invoice.php
Hier ist die Anpassung für das Erstellungsdatum der Rechnung.
Sry, das mit dem Masterbranch war keine Absicht!
Viele Grüße
Patrick
> IP-216 Invoice creation time is now saved in invoice_time_created

- application/modules/setup/sql/008_1.3.0.sql
Datenbankanpassung IP-216 Invoice_time_created
> IP 216 Invoice_created Time added

- application/language/english/ip_lang.php
- application/modules/invoices/views/view.php
- application/modules/quotes/models/mdl_quotes.php
- application/modules/quotes/views/view.php
- application/modules/settings/views/partial_settings_quotes.php
IP-243. Now, you can set up default notes for new quotes.
IP-242. New structure for invoices and quotes.
> IP-243 and IP-242 done

- application/modules/clients/views/form.php
I also enlarge a little a input-box for this client_name
> Fix little mistake in lang key name in client form

- application/modules/invoices/views/partial_item_table.php
- application/modules/invoices/views/view.php
Accidentally submitted #228 but this is the fix for another issue with the id [IP-295](https://development.invoiceplane.com/browse/IP-295)
> This is the correct IP-286 Discount input fields are not disabled on read-only

- application/modules/invoices/views/partial_item_table.php
> Correct fix for IP-295 - Items can be deleted even if in read-only

- application/modules/invoices/models/mdl_invoice_amounts.php
- application/modules/quotes/models/mdl_quote_amounts.php
- application/modules/quotes/models/mdl_quote_item_amounts.php
Also fixed some calculations which were not applied correctly.
> IP-288 - Invoice discounts are only calculated if invoice tax is set

- application/core/Base_Controller.php
- application/modules/invoices/controllers/ajax.php
- application/modules/invoices/views/view.php
Also added form validation to the loaded language files.
> IP-294 - Invoices will be set to paid if all item names are left blank

- application/modules/layout/views/layout.php
- application/modules/sessions/models/mdl_sessions.php
> adds company name to username in header

- application/views/invoice_templates/pdf/default-overdue.php
- application/views/invoice_templates/pdf/default-paid.php
- application/views/invoice_templates/pdf/default-payment.php
- application/views/invoice_templates/pdf/default.php
- application/views/invoice_templates/pdf/green.php
- application/views/invoice_templates/pdf/red.php
- application/views/quote_templates/pdf/blue.php
- application/views/quote_templates/pdf/default.php
- application/views/quote_templates/pdf/green.php
- application/views/quote_templates/pdf/red.php
Translated labels now have enough space.
> change invoice/quote heder widths 70/30 to 60/40

- application/modules/upload/controllers/upload.php
> Fix array syntax error in upload module

- application/modules/invoices/models/mdl_invoice_amounts.php
- application/modules/quotes/models/mdl_quote_amounts.php
This/Last Quarter from current year.
> Dashboard "This/Last Quarter" listing fix

- application/modules/settings/models/mdl_settings.php
I think this fix is obvious :)
> fix set_setting()

- application/modules/invoices/models/mdl_invoices.php
- application/modules/sessions/views/session_login.php
- application/modules/sessions/views/session_new_password.php
- application/modules/sessions/views/session_passwordreset.php
> use jquery-1.11.2 in sessions module (not 1.11.1)

- application/modules/sessions/views/session_login.php
I've added type="email" to show the email keyboard on mobile devices. Also made it remember what you submit so that if you submit a wrong password, you don't have to re-write your email address and vice-versa.
> Update email input type and remember values

- application/modules/clients/views/view.php
- Fixed an issue where a stray div was left after removing code (PR:
#285) and was causing the menu in the view clients page to not function.
- Removed stray quote
> Fixed menu bug

- application/errors/error_php.php
An updated PHP error page.
- Style block added
- Classes added
- unordered list instead of paragraphs
- removed h4. Seemed arbitrary to use a h4.
> Update PHP error page

- application/modules/layout/views/layout.php
- application/modules/layout/views/layout_guest.php
Was not obvious what the sidebar items were, they now have tooltips.
> Added tooltips to sidebar items

- application/modules/invoices/views/view.php
Invoice attachment improvement: replace white spaces to '_' in filename after upload in download and delete buttons, fix formatting and remove alert window in download button
> Invoice attachment improvement: replace whitespaces to '_' in filename

- application/helpers/number_helper.php
- application/modules/payments/views/form.php
IP-328 - Removed format_thousands_separator() as it prevents using the space character as a thousand separator
> IP-328 - Removed format_thousands_separator() function

- application/language/english/ip_lang.php
- application/modules/invoices/controllers/ajax.php
- application/modules/invoices/controllers/cron.php
- application/modules/invoices/models/mdl_invoices.php
- application/modules/invoices/models/mdl_invoices_recurring.php
- application/modules/invoices/views/modal_create_recurring.php
> IP-354 -  Recurring Invoice: set "Invoices Due After" and "Email Template" in recuring invoices

- application/modules/setup/models/mdl_setup.php
- application/modules/setup/sql/016_1.5.0.sql
> IP-353: EmailToSMS feature is missing SQL table modifications, which is causing errors on save

- application/modules/guest/views/quotes_view.php
New lines to html br in guest quote view
> New lines to html br in guest quote view

- application/helpers/mpdf_helper.php
Cherry picked #350 into the 1.4.7 branch
> IP-400 Fix null password PDF protection

- application/modules/invoices/controllers/ajax.php
- application/modules/invoices/controllers/cron.php
- application/modules/invoices/models/mdl_invoice_amounts.php
- application/modules/invoices/models/mdl_invoice_tax_rates.php
- application/modules/invoices/models/mdl_invoices.php
- application/modules/products/controllers/products.php
- application/modules/products/models/mdl_products.php
- application/modules/products/views/form.php
- application/modules/quotes/controllers/ajax.php
- application/modules/quotes/models/mdl_quote_items.php
- application/modules/settings/models/mdl_settings.php
- application/modules/setup/sql/019_1.4.7.sql
IP-417 - Improve product database handling
IP-413 - Tax does not get copied on recurring invoices
IP-322 - Invoice item_name database field should be larger...
IP-303 - Incorrect decimal value: '' for column 'item_discount_amount'
> Solves various issues

- application/views/invoice_templates/public/InvoicePlane_Web.php
Added a \&nbsp; between invoice and invoice_number.
> Fix for IP-434

- application/modules/payments/models/mdl_payments.php
[IP-436] Recurring Invoices - Not able to add additional customer payments
> [IP-436] Recurring Invoices - Not able to add additional customer payments

- .gitignore
- application/modules/layout/views/layout.php
> IP-446 Datepicker not properly responding to "Today" button

- application/modules/sessions/controllers/sessions.php
> Addition to #418

- application/modules/reports/controllers/reports.php
- application/views/reports/sales_by_client.php
Added From/To date to report header, on the same line with title to save space.
Reference: [IP-464](https://development.invoiceplane.com/browse/IP-464)
> Added From/To date to report header

- application/modules/reports/controllers/reports.php
- application/modules/reports/views/invoice_aging_index.php
- application/modules/reports/views/payment_history_index.php
- application/modules/reports/views/sales_by_client_index.php
- application/modules/reports/views/sales_by_year_index.php
- application/views/reports/payment_history.php
- application/views/reports/sales_by_client.php
- application/views/reports/sales_by_year.php
* adds from/to dates to all reports
* improves report views and backend code
> Improves the fix for IP-464

- application/modules/invoices/views/partial_item_table.php
The default setting has no effect i change this
> add default_item_tax_rate setting to output - IP-481

- application/helpers/pdf_helper.php
- application/modules/clients/controllers/Clients.php
- application/modules/clients/views/view.php
- application/modules/custom_fields/models/Mdl_client_custom.php
- application/modules/guest/controllers/View.php
- application/views/invoice_templates/pdf/InvoicePlane - overdue.php
- application/views/invoice_templates/pdf/InvoicePlane - paid.php
- application/views/invoice_templates/pdf/InvoicePlane.php
- application/views/invoice_templates/public/InvoicePlane_Web.php
- assets/core/scss/_core.scss
- Fixes Custom Values bug for clients
- Allow two clients with the same name, but a different surname "Denys Vitali", "Denys", "Denys AAA" are accepted, "Denys Vitali" (again) is not, "Denys" (again) neither
- Format client in headerbar: The client name is now shown fully (Name + Surname) in the headerbar
- Format client in pdf and web invoice: Now the client name (if it has a surname) is shown in its full in both pdf and web invoice
- Fix for a graphical bug in Clients -> View -> Options: when Option was clicked on the latest elements of result, the small option dialog was cut in half
> Various bugfixes and improvements

- application/helpers/mailer_helper.php
- application/helpers/pdf_helper.php
- application/modules/guest/controllers/Invoices.php
- application/modules/guest/controllers/Quotes.php
- application/modules/guest/controllers/View.php
- application/modules/guest/views/invoices_index.php
- application/modules/guest/views/invoices_view.php
- application/modules/guest/views/quotes_index.php
- application/modules/guest/views/quotes_view.php
- application/modules/invoices/controllers/Invoices.php
- application/modules/quotes/controllers/Ajax.php
- application/modules/quotes/models/Mdl_quotes.php
- application/modules/quotes/views/modal_change_client.php
- application/modules/quotes/views/modal_create_quote.php
- application/modules/reports/controllers/Reports.php
- application/modules/reports/models/Mdl_reports.php
- application/modules/users/controllers/Ajax.php
- application/modules/users/controllers/Users.php
- application/modules/users/models/Mdl_user_clients.php
- application/modules/users/views/modal_user_client.php
- application/modules/users/views/partial_user_client_table.php
- application/views/invoice_templates/public/InvoicePlane_Web.php
- application/views/reports/invoice_aging.php
- application/views/reports/sales_by_client.php
- index.php
- uploads/temp/.gitignore
- uploads/temp/.htaccess
Includes:
- Guest can now view Sumex PDFs, client_id are now used almost globally (maybe a full code review of the v1.5.0 branch may be needed to spot more places where client_name is used), format_client is now used in the guest part
- Allow mailer to send Sumex PDF: now if the invoice is of type Sumex (has a sumex_id != NULL), the sent email will include the Sumex Generated PDF as attachment
- Better invoice filename + autocleanup: On every page load the `uploads/temp/` dir is cleaned up for leftover .pdf files. Sumex Invoices generated have now a better file name, composed like the following
`Invoice_INVOICENUMBER_6a4a21a.pdf` where `6a4a21a` are the first 8 chars of the sha1 sum of generated file.
- Fix reports, add format_client: Adds format_client to reports, orders by name + …
> General Improvements

- application/helpers/client_helper.php
- application/modules/guest/views/invoices_view.php
- application/modules/guest/views/quotes_view.php
- application/modules/products/views/modal_product_lookups.php
- application/modules/users/controllers/Ajax.php
- application/modules/users/controllers/Users.php
- application/modules/users/models/Mdl_users.php
- application/modules/users/views/form.php
- application/modules/users/views/modal_user_client.php
- application/modules/users/views/partial_user_client_table.php
- application/views/quote_templates/public/InvoicePlane_Web.php
Also fixes handling for the user <> client relation
> Adds approve/reject buttons to quotes (IP-497)

- application/views/quote_templates/public/InvoicePlane_Web.php
As per slack conversation: https://invoiceplane.slack.com/archives/general/p1489097449000177
> Remove quote payment option

- application/config/config.php
- application/modules/layout/views/includes/head.php
- application/modules/users/controllers/Ajax.php
- application/modules/users/controllers/Users.php
- application/modules/users/views/form.php
- application/modules/users/views/modal_user_client.php
- application/modules/users/views/partial_user_client_table.php
- assets/core/js/scripts.js
Also implements token update for all forms
> IP-485 - Updates CSRF implementation for client user modal

- application/modules/layout/views/includes/navbar.php
- composer.lock
> Fix for a XSS vulnerability (IP-462)

- application/language/english/ip_lang.php
- application/modules/clients/controllers/Ajax.php
- application/modules/settings/views/partial_settings_general.php
https://community.invoiceplane.com/t/topic/4471/3
https://github.com/InvoicePlane/InvoicePlane/pull/503
> Added OPTIONNAL setting to return more results searching clients names - IP-544

- application/modules/mailer/helpers/phpmailer_helper.php
Improve spam scores by including plain text email body
> Add simple plain text body to email (IP-549)

- application/helpers/mailer_helper.php
- application/helpers/template_helper.php
- application/modules/custom_fields/models/Mdl_custom_fields.php
Make custom fields ({{{ip_cf_x}}}) available again in email templates
> IP-551 - Make custom fields ({{{ip_cf_x}}}) available again in email templates

- application/modules/custom_fields/models/Mdl_invoice_custom.php
- application/modules/invoices/models/Mdl_invoices.php
This should fix [IP-555](https://development.invoiceplane.com/browse/IP-555) and [IP-556](https://development.invoiceplane.com/browse/IP-556)  
More testing is required, but looks good to me
cc/ @musapinar @kovah
> Fix IP-555 and IP-556

- application/modules/guest/views/payment_information.php
- application/modules/invoices/views/partial_invoice_archive.php
- application/modules/layout/views/layout.php
- application/modules/layout/views/layout_guest.php
- application/modules/layout/views/setup.php
https://www.w3.org/wiki/The_HTML_head_element
> fixed doctype tag

- application/views/quote_templates/public/InvoicePlane_Web.php
https://community.invoiceplane.com/t/topic/4514/8
> fixed an issue where guest could not approve/reject quote

- application/modules/invoices/models/Mdl_invoice_tax_rates.php
an extra condition has been added since the bug happened on both the "Recurring invoices" feature and the "Copy this invoice" feature.
https://community.invoiceplane.com/t/topic/4613/4
> fixed an issue on tax calculation

- application/core/Validator.php
- application/modules/custom_fields/models/Mdl_custom_fields.php
- application/modules/custom_values/models/Mdl_custom_values.php
- application/modules/invoices/controllers/Cron.php
- application/modules/invoices/models/Mdl_invoices.php
- application/modules/invoices/models/Mdl_items.php
- application/modules/invoices/views/partial_item_table.php
Corrects toggle for recurring items (IP-560 and #524)
Fix the validator for multi-choices
Fix the custom field handling for values (IP-573)
Fix the recurring invoices module (IP-572)
> Fix issues IP-560, IP-573 and IP-572

- application/modules/custom_fields/models/Mdl_custom_fields.php
This fixes the 500 error on php5.6
> Update Mdl_custom_fields.php (IP-574)

- application/modules/guest/controllers/View.php
The same custom fields will be available as what is available in a PDF
template.
Forum topic: https://community.invoiceplane.com/t/topic/4223/26
> Make $custom_fields available in public templates (IP-605)

- application/modules/invoices/views/view_sumex.php
- application/modules/products/views/modal_product_lookups.php
Additional layout ond code fixes for sumex implementation
>  Allow product search with enter key (IP-590) 

- application/modules/clients/views/script_select2_client_id.js
- application/modules/invoices/views/modal_copy_invoice.php
- application/modules/invoices/views/modal_create_invoice.php
- application/modules/layout/views/layout.php
- application/modules/projects/views/form.php
+ various smaller code corrections
> Fix escaping for create quote/invoice modals (IP-606)

- application/modules/projects/views/form.php
> fix customer not selectable (IP-613)

- application/modules/guest/controllers/Payment_handler.php
Only tested with Mollie payment gateway. 
https://community.invoiceplane.com/t/topic/4625/23
> IP-612 Fixed Mollie payments

- assets/core/js/scripts.js
https://select2.org/programmatic-control/add-select-clear-items#selecting-options
According to the doc, the select2 need the .trigger('change') to update the selected option. That's why it doesn't updated when changing the email templates
> [IP-621] - select2 for pdf templates not changing when email templates

- application/modules/invoices/models/Mdl_invoices.php
- application/modules/quotes/models/Mdl_quotes.php
Increase the key length to avoid duplicate and a if statement to allow import (as they have no invoice_group_id they don't need to enter in the if statement)
> [IP-510] - Import function not working

- application/helpers/echo_helper.php
- application/modules/layout/views/includes/head.php
- application/modules/settings/controllers/Settings.php
- application/modules/settings/models/Mdl_settings.php
- application/modules/settings/models/Mdl_versions.php
- application/modules/settings/views/partial_settings_updates.php
Also corrects scripts for update checks in the settings view
> Append version to asset paths to prevent browser cache issues (IP-641) 

- application/modules/invoices/controllers/Ajax.php
- application/modules/invoices/controllers/Invoices.php
- application/modules/invoices/models/Mdl_items.php
- application/modules/invoices/views/modal_delete_invoice.php
- application/modules/invoices/views/partial_item_table.php
- application/modules/invoices/views/view.php
- application/modules/quotes/controllers/Ajax.php
- application/modules/quotes/controllers/Quotes.php
- application/modules/quotes/models/Mdl_quote_items.php
- application/modules/quotes/views/modal_delete_quote.php
- application/modules/quotes/views/partial_item_table.php
- application/modules/quotes/views/view.php
Deleting items will also not reload the page anymore to prevent data loss if changes are not saved yet.
> [IP-649] Fix quote/invoice and item deletion issues

- application/modules/invoices/models/Mdl_invoices.php
also corrects custom field copying
> Fix credit invoice generation (IP-648)

- application/modules/sessions/controllers/Sessions.php
Please check the following steps to submit your pull request. If you have any questions please read the contribution guide available at https://go.invoiceplane.com/contribguide or join the community forums or the Slack channel.
You can check items by changing `[ ]` to `[-]`.
You can remove this first paragraph but please keep the following checklist even if it's incomplete. Pull requests without the checklist will be rejected.
If you can't check all checklist items please add `[WIP]` in front of your title.
Fix a typo in the previous IP-596.
> Fix Typo in [IP-596]

- application/modules/settings/views/partial_settings_updates.php
> Fix the update check (IP-656)

- application/language/english/ip_lang.php
- application/modules/invoices/views/partial_item_table.php
- application/modules/invoices/views/view.php
- application/modules/quotes/views/partial_item_table.php
- application/modules/quotes/views/view.php
> Implement correct quote/invoice tax rate deletion (IP-649)

- application/helpers/custom_values_helper.php
- application/modules/custom_fields/models/Mdl_custom_fields.php
- application/modules/custom_values/models/Mdl_custom_values.php
> Bool custom field receive wrong value from other field (IP-640)

- application/modules/invoices/views/index_recurring.php
- application/modules/layout/views/includes/head.php
- application/modules/user_clients/views/field.php
> Fixes for IP-686 IP-680 and IP-687

- assets/invoiceplane/sass/style.scss
- assets/invoiceplane_blue/sass/style.scss
Not sure if this is the correct dest branch, noticed this while building CSS initially.
> Updating build paths.

- application/modules/invoices/models/Mdl_invoices.php
- application/modules/quotes/models/Mdl_quotes.php
https://development.invoiceplane.com/browse/IP-679
I also fix a little typo I fail on the first PR :)
> [IP-679] - Duplicate invoice number generation

- application/modules/settings/views/partial_settings_general.php
> [IP-688] Make 'default_list_limit' more customizable

- application/modules/sessions/controllers/Sessions.php
Log logins.
To be able to block brute-force attacks with fail2ban.
> [IP-691] Provide new log file for fail2ban

- application/modules/quotes/controllers/Ajax.php
- application/modules/quotes/controllers/Quotes.php
- application/modules/quotes/models/Mdl_quotes.php
- assets/core/scss/_core.scss
- assets/invoiceplane/sass/_ip_variables.scss
- assets/invoiceplane_blue/sass/_ip_variables.scss
The quote state indicates, that for an accepted quote
an invoice was written.
When an invoiced is created from a quote the
state of the quote gets changed automatically.
Closes [IP-636]
> [IP-636] Add another quote state "invoiced"

- application/modules/invoices/controllers/Invoices.php
- application/modules/quotes/controllers/Quotes.php
- https://development.invoiceplane.com/browse/IP-700
> [IP-700] - IP doesn’t generate invoice number after download

- .gitignore
- htaccess
- package-lock.json
> Update gitignore, htaccess (add . before filename) package-lock.json

- app/Modules/MailQueue/Support/MailQueue.php
> [IP2-62] Email form requires CC / BCC fields

- application/modules/quotes/views/index.php
> [IP-724] Add "Invoiced" button in the View Quotes page.

- application/modules/clients/views/partial_client_table.php
- application/modules/custom_fields/views/index.php
- application/modules/custom_values/views/index.php
- application/modules/dashboard/views/index.php
- application/modules/email_templates/views/index.php
- application/modules/families/views/index.php
- application/modules/guest/views/invoices_index.php
- application/modules/guest/views/partial_invoices_table.php
- application/modules/guest/views/partial_quotes_table.php
- application/modules/guest/views/payments_index.php
- application/modules/invoice_groups/views/index.php
- application/modules/invoices/views/partial_invoice_archive.php
- application/modules/invoices/views/partial_invoice_table.php
- application/modules/payment_methods/views/index.php
- application/modules/payments/views/online_logs.php
- application/modules/payments/views/partial_payment_table.php
- application/modules/products/views/index.php
- application/modules/products/views/partial_product_table_modal.php
- application/modules/projects/views/index.php
- application/modules/projects/views/view.php
- application/modules/quotes/views/partial_quote_table.php
- application/modules/tasks/views/index.php
- application/modules/tasks/views/partial_task_table_modal.php
- application/modules/tax_rates/views/index.php
- application/modules/units/views/index.php
- application/modules/user_clients/views/field.php
- application/modules/users/views/index.php
Class "table-hover" has been added to most tables in IP to help users reading the correct row.
> [IP-721] Improve tables readability with hover

- application/language/english/ip_lang.php
- application/modules/user_clients/views/field.php
The warning message shown when clicking the Remove button in the "Assigned Clients" table is the one for deleting invoices: "If you delete this invoice...". Create and display a proper warning message.
> [IP-725] Fix warning message when deleting a user-client relationship

- application/modules/invoices/controllers/Ajax.php
- application/modules/quotes/controllers/Ajax.php
> [IP-601]  Keep and save item price in quotes & invoices when quantity is set to zero.

- application/modules/clients/views/form.php
- application/modules/invoices/views/archive.php
- application/modules/invoices/views/modal_create_invoice.php
- application/modules/invoices/views/view.php
- application/modules/payments/views/form.php
- application/modules/quotes/views/modal_create_quote.php
- application/modules/quotes/views/view.php
- application/modules/settings/views/partial_settings_email.php
- application/modules/settings/views/partial_settings_general.php
- application/modules/settings/views/partial_settings_invoices.php
- application/modules/settings/views/partial_settings_projects_tasks.php
- application/modules/settings/views/partial_settings_quotes.php
- application/modules/settings/views/partial_settings_taxes.php
- application/modules/tasks/views/form.php
> [IP-718]  Missing closing ">" symbox in div tag

- application/modules/payments/views/partial_payment_table.php
Trivial fix to right-align the amounts column in the View Payments table (payments/index).
> [IP-730] Right-align amount in View Payments table

- application/modules/settings/controllers/Ajax.php
Remove the function test_mail() used during development for testing purposes from the distributed files where it is neither needed nor used.
> [IP-732] Remove unused function test_mail()

- application/modules/invoices/views/modal_copy_invoice.php
Change the ID of the datepicker input of the modal windows to a different value than the ID of the datepicker in the main page so that they don't clash, and use the new ID in the Javascript code that creates the new invoice.
> [IP-575] When copying an invoice, set the date as selected in the modal

- application/modules/invoices/views/view.php
- application/modules/quotes/views/view.php
> [IP-707] Properly escape password fields for quotes and invoices

- application/modules/dashboard/views/index.php
- application/modules/invoices/views/partial_invoice_table.php
- application/modules/invoices/views/view.php
> [IP-739] Implement icons for recurring invoices

- application/modules/clients/views/partial_client_table.php
- assets/core/scss/_core.scss
- assets/invoiceplane/sass/_ip_variables.scss
- assets/invoiceplane_blue/sass/_ip_variables.scss
> [IP-720] Improve the visibility of client status in table of clients.

- application/helpers/date_helper.php
- application/modules/settings/views/partial_settings_email.php
- application/modules/settings/views/partial_settings_general.php
- application/modules/settings/views/partial_settings_invoices.php
- application/modules/settings/views/partial_settings_online_payment.php
- application/modules/settings/views/partial_settings_projects_tasks.php
- application/modules/settings/views/partial_settings_quotes.php
- application/modules/settings/views/partial_settings_taxes.php
- application/modules/settings/views/partial_settings_updates.php
- assets/core/scss/_core.scss
> Improvements for settings module

- application/modules/guest/controllers/View.php
Bug fix contributed by user gregorb in post no. 7 of the topic:
https://community.invoiceplane.com/t/topic/6186
> [IP-741] Custom fields not available in quote web template

- application/language/english/ip_lang.php
- application/modules/settings/views/partial_settings_invoices.php
- application/modules/settings/views/partial_settings_quotes.php
[IP-747] Minor cosmetic changes to the General Settings forms
Minor cosmetic changes to the general settings forms like:
* Quote tab header is "General Settings" and should be "Quote".
* "Quote template" section header is duplicated, and the first one should be "PDF Settings".
* Replace "Invoice Template" with "Invoice Templates".
* Create the language string when required.
> [IP-747] Minor cosmetic changes to the General Settings forms

- composer.json
- composer.lock
Fixing a few things that I'm noticing before bringing the IT version up-to-date.
-updated fpdi version, is erroring when re-downloading deps.
> Fixing a few things

- application/modules/clients/controllers/Clients.php
It seems this is the expected behavior, instead of the currently hard-coded `20`
-------
> respect "Number of Items in Lists" setting when displaying items in client views

- application/helpers/mailer_helper.php
- application/helpers/mpdf_helper.php
- application/helpers/pdf_helper.php
- application/language/english/ip_lang.php
- application/modules/guest/controllers/Invoices.php
- application/modules/guest/views/invoices_view.php
- application/modules/invoices/controllers/Invoices.php
- application/modules/invoices/views/view.php
- composer.lock
I added the feature to merge attachments to output invoice pdf per default. Lets discuss if we should add a checkbox or similar to enable/disable this feature. 
I was not able to create an issue because the ssl cert of the issue tracker is not valid anymore
> Add attachments to pdf output invoice file

- application/modules/guest/controllers/View.php
- application/modules/upload/controllers/Upload.php
This is the quick fix for #734
As the full path is never used, we just decided to remove it entirely and not show it at all.
> Don't show upload-path

- uploads/.gitignore
- uploads/archive/.gitignore
- uploads/archive/index.html
- uploads/customer_files/.gitignore
- uploads/customer_files/index.html
- uploads/import/.gitignore
- uploads/import/index.html
- uploads/index.html
- uploads/temp/.gitignore
- uploads/temp/index.html
- uploads/temp/mpdf/.gitignore
- uploads/temp/mpdf/index.html
I couldn't figure out how are you working with the branches, so i targeted the develop branch that seems to be the only active one.
The `index.html` files in the folders prevent a poorly configured server from allowing browsers to list the content of the folder. I hope the contribution is ok.
> fix to CVE-2021-29024 #735

- application/modules/quotes/views/partial_itemlist_responsive.php
- assets/core/img/file-icons/default.svg
- assets/core/img/file-icons/file-audio.svg
- assets/core/img/file-icons/file-document.svg
- assets/core/img/file-icons/file-pdf.svg
- assets/core/img/file-icons/file-presentation.svg
- assets/core/img/file-icons/file-spreadsheet.svg
- assets/invoiceplane/sass/_custom_styles.scss
> fix minor flaws in quotes itemlist view

- application/modules/email_templates/views/template-tags.php
As found in logfile:
pim@billing:/var/www/html$ tail application/logs/log-2021-12-30.php 
ERROR - 2021-12-30 19:32:04 --> Could not find the language line "subtot al"
ERROR - 2021-12-30 19:32:04 --> Could not find the language line "subtot al"
ERROR - 2021-12-30 19:32:54 --> Could not find the language line "subtot al"
ERROR - 2021-12-30 19:32:54 --> Could not find the language line "subtot al"
> Trivial typo fix

- application/modules/invoices/controllers/Cron.php
> Fix bug with recurring invoices dropping discounts

- application/modules/guest/controllers/View.php
Select appropriate pdf template for guest users "download pdf" button.
> Select appropriate pdf template for guest users

- application/config/database.php
- application/core/Base_Controller.php
- application/helpers/date_helper.php
- application/helpers/echo_helper.php
- application/modules/clients/views/form.php
- application/modules/dashboard/views/index.php
- application/modules/guest/views/gateway/stripe.php
- application/modules/import/models/Mdl_import.php
- application/modules/invoices/controllers/Cron.php
- application/modules/invoices/models/Mdl_invoice_amounts.php
- application/modules/invoices/views/view_sumex.php
- application/modules/mailer/controllers/Mailer.php
- application/modules/quotes/models/Mdl_quote_amounts.php
- application/modules/settings/controllers/Settings.php
- application/modules/settings/models/Mdl_settings.php
- application/modules/settings/views/partial_settings_general.php
- application/modules/settings/views/partial_settings_online_payment.php
- application/modules/setup/controllers/Setup.php
- application/modules/tasks/views/form.php
- application/modules/tasks/views/index.php
- application/third_party/MX/Controller.php
- application/third_party/MX/Loader.php
- application/third_party/MX/Modules.php
- composer.json
- composer.lock
- index.php
- ipconfig.php.example
This Pull-Request merges vtq221's work and Ordissimo's work.
It requests to pull that work into the feature/issue-798 branch to prepare ourselves for the PHP 8.1 compatibility release.
> [IP-798]: Prepare for PHP 8.1 compatibility release

- application/config/database.php
- application/core/Base_Controller.php
- application/helpers/date_helper.php
- application/helpers/echo_helper.php
- application/modules/clients/views/form.php
- application/modules/dashboard/views/index.php
- application/modules/guest/views/gateway/stripe.php
- application/modules/import/models/Mdl_import.php
- application/modules/invoices/controllers/Cron.php
- application/modules/invoices/models/Mdl_invoice_amounts.php
- application/modules/invoices/views/view_sumex.php
- application/modules/mailer/controllers/Mailer.php
- application/modules/quotes/models/Mdl_quote_amounts.php
- application/modules/settings/controllers/Settings.php
- application/modules/settings/models/Mdl_settings.php
- application/modules/settings/views/partial_settings_general.php
- application/modules/settings/views/partial_settings_online_payment.php
- application/modules/setup/controllers/Setup.php
- application/modules/tasks/views/form.php
- application/modules/tasks/views/index.php
- application/third_party/MX/Controller.php
- application/third_party/MX/Loader.php
- application/third_party/MX/Modules.php
- composer.json
- composer.lock
- index.php
Reverts InvoicePlane/InvoicePlane#859
> Revert "[IP-798]: Prepare for PHP 8.1 compatibility release"

- application/helpers/echo_helper.php
> fixes bug #875

- application/modules/guest/views/payment_information.php
> load the stripe library by using the base_url #883

- application/helpers/date_helper.php
- application/libraries/ZugferdXml.php
- application/modules/invoices/models/Mdl_invoices.php
- application/modules/invoices/models/Mdl_invoices_recurring.php
- application/modules/setup/models/Mdl_setup.php
- application/modules/setup/sql/036_1.6.sql
Improves compatibility with MySQL version 8 by comparing to NULL dates instead of '0000-00-00'
> MySQL 8 compatibility

- ipconfig.php.example
closes issue #894 
see https://github.com/InvoicePlane/InvoicePlane/issues/894#issuecomment-1339149433. Solution by @morj-uio
> updated ipconfig template #894

- application/modules/setup/controllers/Setup.php
> fixes issue #907

- application/modules/invoices/controllers/Ajax.php
- application/modules/payments/controllers/Ajax.php
- application/modules/products/controllers/Ajax.php
- application/modules/quotes/controllers/Ajax.php
> fix possible vulnerabilities #902

- assets/core/js/scripts.js
Speed up all actions by saving the form with the Ctrl + S keyboard shortcut instead of having to click the button with your mouse. It's a common feature nowadays.
> Detect Ctrl + S keyboard shortcut and save the form

- application/modules/quotes/models/Mdl_quote_items.php
This patch never made it to production last time, so now we're making sure it will
Refs #914 supersedes #717
> Here is my patch to make values from the product table also available in the pdf template for quotes:
> Make product.* available in quotes

- .gitignore
- application/language/english/ip_lang.php
- application/modules/invoices/models/Mdl_invoices.php
- application/modules/mailer/controllers/Mailer.php
- application/modules/settings/views/partial_settings_invoices.php
Reverts InvoicePlane/InvoicePlane#924
> Revert "IP-895: Option to Initiate Terms When Sending Invoice (WIP)"

- application/modules/clients/views/form.php
- application/modules/custom_fields/views/form.php
- application/modules/custom_values/views/edit.php
- application/modules/custom_values/views/new.php
- application/modules/email_templates/views/form.php
- application/modules/families/views/form.php
- application/modules/invoice_groups/views/form.php
- application/modules/invoices/views/modal_create_invoice.php
- application/modules/payment_methods/views/form.php
- application/modules/payments/views/form.php
- application/modules/products/views/form.php
- application/modules/projects/views/form.php
- application/modules/quotes/views/modal_add_quote_tax.php
- application/modules/quotes/views/modal_create_quote.php
- application/modules/tasks/views/form.php
- application/modules/tax_rates/views/form.php
- application/modules/units/views/form.php
- application/modules/user_clients/views/new.php
- application/modules/users/views/form.php
- application/modules/users/views/form_change_password.php
> IP-911: required fields check

- application/modules/setup/sql/037_1.6.1
> added versioning file

- application/modules/clients/controllers/Ajax.php
> IP-940: unicode inside select

- application/modules/invoices/controllers/Ajax.php
- application/modules/payments/controllers/Ajax.php
- application/modules/products/controllers/Ajax.php
- application/modules/quotes/controllers/Ajax.php
Some more security fixes.
We will post the fixes once the full release comes out
Affected files:
|           |   FileName     | FieldName | Fix type  |
|-	        |-	    |-            |-	            |
|  X   |`invoices/controllers/Ajax`| ``  |  |
|  X   |`payments/controllers/Ajax`| `` |  |
|  X   |`products/controllers/Ajax`| ``  |  |
|  X   |`quotes/controllers/Ajax`| ``  |  |
> 2023 23011

- application/modules/invoices/controllers/Cron.php
An issue was reported that sometimes Recurring Invoices were not being (re-) generated.
This PR adds logging for if IP_DEBUG=true
Addresses #766
> [IP-766] add extra logging when IP_DEBUG=true for the Recurring invoices

- application/modules/clients/views/script_select2_client_id.js
- application/modules/projects/views/form.php
Fix project doesn't show client and delete useless console log
> fix #971 & delete useless console log

- application/helpers/trans_helper.php
> #1034: Fix error where default_language at some point switches to English

- README.md
Link to demo on homepage so logindata is provided and adjust some wordings
> Slight improvements to README.md

- application/modules/sessions/controllers/Sessions.php
> fixes issue #1070

- application/modules/dashboard/views/index.php
Issue: https://github.com/InvoicePlane/InvoicePlane/issues/1072
* [ x] My code follows the code formatting guidelines.
* [ x] I have an issue ID for this pull request.
* [x ] I selected the corresponding branch.
* [x ] I have rebased my changes on top of the corresponding branch.
* [ x] Bugfix
> [1072] Fixed broken customer-link in projects-widget on dashboard.

- application/language/english/ip_lang.php
- application/modules/settings/views/partial_settings_invoices.php
> added information on theming

- application/modules/quotes/models/Mdl_quotes.php
> copy all fields available in quotes #998

- application/modules/clients/controllers/Clients.php
- application/modules/clients/views/view.php
- assets/core/scss/_core.scss
This PR add the function to paginate in clients detail the tabs for quotes invoices and payments
#1083 
If a client have more than 20 invoices, payments or quotes, only the newest 20 was shown
> [IP-1083]: Add pagination for tabs in client detail

- application/modules/clients/Enums/ClientTitleEnum.php
- application/modules/clients/controllers/Clients.php
- application/modules/clients/views/form.php
> enum example

- application/modules/invoices/models/Mdl_invoices.php
> [IP-1096] Payments array variable gets lost for invoices

- application/core/Admin_Controller.php
- application/modules/clients/controllers/Clients.php
- application/modules/custom_fields/controllers/Custom_fields.php
- application/modules/email_templates/controllers/Email_templates.php
- application/modules/families/controllers/Families.php
- application/modules/import/controllers/Import.php
- application/modules/invoice_groups/controllers/Invoice_groups.php
- application/modules/payment_methods/controllers/Payment_methods.php
- application/modules/payments/controllers/Payments.php
- application/modules/products/controllers/Products.php
- application/modules/projects/controllers/Projects.php
- application/modules/tasks/controllers/Tasks.php
- application/modules/tax_rates/controllers/Tax_rates.php
- application/modules/units/controllers/Units.php
- application/modules/users/controllers/Users.php
- pint.json
So when a form is posted it needs to be checked for nastiness. This function (right now in the Admin_Controller) will do that
To Be Determined
Whenever I post my form, i want to make sure that any nastiness like "onmouseover=alert('XSS') or something" doesn't get through, this function that I added in the Admin_Controller will make an attempt to strip out those things
> add function to check post variables

- application/helpers/number_helper.php
- application/language/english/ip_lang.php
- application/modules/invoices/views/partial_itemlist_responsive.php
- application/modules/invoices/views/partial_itemlist_table.php
- application/modules/quotes/views/partial_itemlist_responsive.php
- application/modules/quotes/views/partial_itemlist_table.php
- application/modules/settings/views/partial_settings_general.php
- application/modules/setup/sql/038_1.6.2.sql
- application/views/invoice_templates/pdf/InvoicePlane - overdue.php
- application/views/invoice_templates/pdf/InvoicePlane - paid.php
- application/views/invoice_templates/pdf/InvoicePlane.php
- application/views/invoice_templates/public/InvoicePlane_Web.php
- application/views/quote_templates/pdf/InvoicePlane.php
- application/views/quote_templates/public/InvoicePlane_Web.php
> [IP-731]: Add another digit for quantity (new version)

- resources/docker/php-fpm/Dockerfile
- resources/docker/php-fpm/xdebug.ini
Just the improved Dockerfile (and xdebug.ini) to resolve issue refs #1010
> [IP-1010]: Add php-dom and php-xml to the Dockerfile

- .github/workflows/docker-publish.yml
#1097 
Improvement, makes deploying easier by providing a pre-built docker container.
> add docker publish workflow

- application/helpers/client_helper.php
- application/language/english/ip_lang.php
- application/modules/clients/views/form.php
See [Clients/Enums/ClientTitleEnum](https://github.com/InvoicePlane/InvoicePlane/blob/development/application/modules/clients/Enums/ClientTitleEnum.php)
> Translate Client "Extra Field Title" to complete #1003

- application/modules/payments/controllers/Payments.php
- application/modules/payments/models/Mdl_payments.php
- application/modules/payments/views/form.php
Fix #1146 
Fix if repost without change get error of number_format(): Arg #1 ($num) must be of type float, string given
modules/payments/views/form.php Function: format_amount
> Fix #1146 after posting a Payments Form when amount > inv. total

- assets/core/js/scripts.js
> Added required input check on full page loaded to 'fix' #1130

- application/modules/setup/models/Mdl_setup.php
- assets/core/js/scripts.js
> bug-fix-#1147-error-on-database-migration

- application/modules/setup/models/Mdl_setup.php
- application/modules/setup/views/upgrade_tables.php
After tested (with real data backup of 1.5.11 version) i get an error 
CI say `Call to undefined method CI_DB_mysqli_driver::_error_message()`
+ Complete https://github.com/InvoicePlane/InvoicePlane/issues/1147
+ [Solve Red screen Of Death of bad DB query in
CI3](https://stackoverflow.com/questions/7843406/codeigniter-how-to-catch-db-errors#54519533)
+ Fix Call to undefined method CI_DB_mysqli_driver::_error_message()
The _error_message() function unexist in CI3.1.13:
`vendor/codeigniter/framework/system/database/DB_driver.php`
+ Indents: tab2spaces
Does it solve a provlem with setup.
+ Now: All setup db query with error return a message and `Try again` button appear,
+ Before: 
++ `Call to undefined method CI_DB_mysqli_driver::_error_message()` or
++ Red Screen Of Death
To test:
+ 1 …
> Fix setup Red Screen Of Death with bad DB query

- application/modules/email_templates/views/template-tags-invoices.php
> Fix missing if-check

- application/modules/email_templates/views/template-tags-invoices.php
> fix problem

- application/modules/invoices/controllers/Invoices.php
> Removed '.pdf' from Invoices.php downloads to fix #1171

- application/core/Base_Controller.php
- application/modules/clients/views/partial_client_table.php
- application/modules/clients/views/view.php
Fix: Delete Client go to 404 page #1182 see [1st commit](https://github.com/InvoicePlane/InvoicePlane/pull/1183/commits/7b804662385fcf5f21ccf925a460bf540fd460f4).
`+` little details (indents and comment in `Base_controller`) see [2nd commit](https://github.com/InvoicePlane/InvoicePlane/pull/1183/commits/5c600e16dd0a71a59f73513fb6df4d9c32d7aebd).
#1182
> Fix summary client delete button go to 404 (link2form)

- application/modules/clients/views/partial_client_table.php
> Fix styling in clients table header #1184

- assets/core/js/scripts.js
`$(document).on('click', '.ajax-loader', function () {` duplicated inside same function.
> Fix #fullpage-loader (Spinner) never showed after save

- application/modules/mailer/helpers/phpmailer_helper.php
> Fix #1196: Send email show blank page (php>=8.2)

- application/config/config.php
- application/helpers/e-invoice_helper.php
- application/helpers/pdf_helper.php
- application/libraries/XMLtemplates/Facturxv10Xml.php
- application/modules/invoices/models/Mdl_invoice_amounts.php
- application/modules/invoices/models/Mdl_item_amounts.php
- application/modules/quotes/models/Mdl_quote_amounts.php
- application/modules/quotes/models/Mdl_quote_item_amounts.php
- ipconfig.php.example
Need to change Discounts calculation to be fully validated facturx.xml
Updated facturxv10Xml template to add discounts
When activate ip debug and get an invoice pdf (and e-invoice are activate)  
To Simplify xml validation alaways `uploads/temp/einvoice_test.xml` are maked
Need delete file when debug is over (see pdf_helper)
And see #1210
> Improve factur-x e-invoices + 2 Discounts calculation modes in ip_config

- application/modules/invoices/views/partial_itemlist_responsive.php
- application/modules/invoices/views/partial_itemlist_table.php
- application/modules/invoices/views/partial_itemlist_table_invoice_discount.php
- application/modules/invoices/views/view_sumex.php
- application/modules/layout/views/partial/itemlist_responsive_item_discount_input.php
- application/modules/layout/views/partial/itemlist_responsive_item_discount_show.php
- application/modules/layout/views/partial/itemlist_table_item_discount_input.php
- application/modules/layout/views/partial/itemlist_table_item_discount_show.php
- application/modules/quotes/views/partial_itemlist_responsive.php
- application/modules/quotes/views/partial_itemlist_table.php
- application/modules/quotes/views/partial_itemlist_table_quote_discount.php
- application/views/invoice_templates/public/InvoicePlane_Web.php
- application/views/quote_templates/public/InvoicePlane_Web.php
+ invoices/views/partial_itemlist_table `*`
+ quotes/views/partial_itemlist_table `*`
+ invoices/views/partial_itemlist_responsive
+ quotes/views/partial_itemlist_responsive
`*` <del>Removed</del> Retailed old thead's (it's displayed none)
+ invoices/views/partial_itemlist_table_invoice_discount.php `*`
+ quotes/views/partial_itemlist_table_invoice_discount.php `*`
+ layout/views/partial/itemlist_table_item_discount_show.php `**`
+ layout/views/partial/itemlist_table_item_discount_input.php `**`
+ layout/views/partial/itemlist_responsive_item_discount_show.php `**`
+ layout/views/partial/itemlist_responsive_item_discount_input.php `**`
`*` Called in amount total table (same 4 table & responsive mode)
`**` Called in quotes|invoices itemlist (One for new and edit)
+ …
> taxes_after_discounts: Improve GUI templates

- application/libraries/XMLtemplates/Facturxv10Xml.php
+ Typo ($filname)
+ For Subject to VAT SpecifiedTaxRegistration 'VA' (vat_id)
+ + not called if all items 100% discount (make taxes = 0)
+ DivisionByZeroError break pdf generation
+ + In `get_invoice_discount_percent()`
+ + Now return percent = '0.01'; // fix by faker (wip)
+ + + See Todo (below)
---
+ Not subject to VAT
+ + `invoice_tax_total` 2 `invoice_item_tax_total`
+ + `invoice_total` 2 `invoice_item_subtotal`
+ Call `getInstance` of CI removed
---
+ Transform get_invoice_discount_percent() to helper
+ + for get/dispatch discount percent vat's rate (of invoice)
+ + to remove `fix by faker (wip)`
---
> WIP Factur-X (Fix for taxes)

- application/helpers/XMLconfigs/Ublexamv20.php
- application/helpers/XMLconfigs/Zugferdv10.php
- application/helpers/XMLconfigs/Zugferdv23.php
- application/helpers/XMLconfigs/Zugferdv23g.php
- application/helpers/e-invoice_helper.php
- application/helpers/pdf_helper.php
See issue #1220
`+` lint (pdf & e-invoice)_helper
> 939 e-invoicing: Shared generator by config (optional parameter)

- application/modules/payments/views/form.php
Maybe solve a problem of #1226 (and probably need PR #1228 to solve completely)
> Remove unattended standardize_amount in payments view form

- application/libraries/MY_Form_validation.php
- application/third_party/MX/Controller.php
- composer.json
- index.php
Minor Changes to work with php 5.4 to 8.4
from auto-maintained codeigniter/framework : 3.1.13
to maintained [pocketarc/codeigniter](https://github.com/pocketarc/codeigniter) : 3.3.0
Need run `composer update` or `composer install`
addresses #1223 #1180 #1009 
Thx CI say :
Your system folder path does not appear to be set correctly.
Please open the following file and correct this: `index.php`
From: codeigniter/framework v3.1.13 (official unmaintened)
`$system_path = 'vendor/codeigniter/framework/system';`
To:  [pocketarc/codeigniter](https://github.com/pocketarc/codeigniter) v3.3.0 (CI3 maintened fork)
`$system_path = 'vendor/pocketarc/codeigniter/system';`
Filename: MX/Controller.php (add $load class var)
+ Old Fix: Creation of dynamic property Setup::$load is deprecated
+ typo indent …
> CodeIgniter3 for php-8.2+ and maintained by pocketarc

- application/helpers/invoice_helper.php
See comment https://github.com/InvoicePlane/InvoicePlane/issues/1128#issuecomment-2600949898
https://github.com/InvoicePlane/InvoicePlane/issues/1128
> fix: amount of the credit transfer cannot be smaller than 0.01 Euro #1128

- Gruntfile.js
- package.json
- yarn.lock
Fixes cross-compilation and removes deprecated node-sass dependency
---
Provide a brief description of the changes made in this pull request.
---
List any related issues or discussions. If applicable, link to an accompanying thread on the forums.
Fixes # (example)
---
Why was this change necessary? Does it solve a problem or improve an existing feature? If this PR fixes an open issue, link to it here.
---
---
Attach relevant screenshots that demonstrate your changes.
---
*Thank you for your contribution to InvoicePlane! We appreciate your time and effort.*
> Replace node-sass with sass

- application/views/invoice_templates/public/InvoicePlane_Web.php
- application/views/quote_templates/public/InvoicePlane_Web.php
Reverts InvoicePlane/InvoicePlane#1343
> Revert "[IP-1340]: wrong quoteinvoice guest download attachment button default template"
